! GENERATED by harness/g33_fixture_v1.py from g33_fixture_v1.json.
! Do not edit: run the generator and commit both outputs.
module g33_fixture_v1
  use, intrinsic :: iso_fortran_env, only: int32
  implicit none
  integer, parameter :: B = 3, K = 4
  character(len=*), parameter :: FIXTURE_ID = 'boundary_mapping_v1'
  character(len=*), parameter :: MANIFEST_SHA256 = '3d07922b98a29ce5cdb4037a8fd77f0f779b8f1441515f45c7d7edd432ce4f05'
  character(len=*), parameter :: FIXTURE_SHA256 = '0b959687ea995b997baf685ab9e51e9ab03c9e1258ac190be8a60326eaddb047'
  character(len=*), parameter :: PARAMETER_SHA256 = 'fb1b87f217b3fdbd8c4decb1471d91883f50a03bd64ee8441a229a0e02b7a869'
  character(len=*), parameter :: FORTRAN_PARAMETER_SHA256 = 'f1008f2ec5629d7dcaa0e5305771163c7b7651cc112b3ceea6a4ad4b06caf39b'

  integer(int32), parameter :: TH_BITS(B,K) = reshape([ &
       int(z'43960000', int32), int(z'43978000', int32), int(z'43990000', int32), int(z'439B8000', int32), &
       int(z'439D0000', int32), int(z'439E8000', int32), int(z'43A10000', int32), int(z'43A28000', int32), &
       int(z'43A40000', int32), int(z'43A68000', int32), int(z'43A80000', int32), int(z'43A98000', int32) &
       ], [B,K])
  integer(int32), parameter :: QV_BITS(B,K) = reshape([ &
       int(z'3A83126F', int32), int(z'3ADED289', int32), int(z'3B2A64C3', int32), int(z'3A83126F', int32), &
       int(z'3ADED289', int32), int(z'3B2A64C3', int32), int(z'3A83126F', int32), int(z'3ADED289', int32), &
       int(z'3B2A64C3', int32), int(z'3A83126F', int32), int(z'3ADED289', int32), int(z'3B2A64C3', int32) &
       ], [B,K])
  integer(int32), parameter :: QC_BITS(B,K) = reshape([ &
       int(z'3951B717', int32), int(z'395D3FE2', int32), int(z'3968C8AC', int32), int(z'A0CE9A81', int32), &
       int(z'398E1501', int32), int(z'3993D966', int32), int(z'39A7C5AC', int32), int(z'39AD8A11', int32), &
       int(z'39B34E77', int32), int(z'39C73ABD', int32), int(z'39CCFF22', int32), int(z'39D2C387', int32) &
       ], [B,K])
  integer(int32), parameter :: QR_BITS(B,K) = reshape([ &
       int(z'391D4952', int32), int(z'3926B93D', int32), int(z'39302928', int32), int(z'3951B717', int32), &
       int(z'395B2703', int32), int(z'396496EE', int32), int(z'3983126F', int32), int(z'3987CA64', int32), &
       int(z'398C825A', int32), int(z'399D4952', int32), int(z'39A20147', int32), int(z'39A6B93D', int32) &
       ], [B,K])
  integer(int32), parameter :: QI_BITS(B,K) = reshape([ &
       int(z'3716FEB5', int32), int(z'371F6230', int32), int(z'3727C5AC', int32), int(z'3749539C', int32), &
       int(z'3751B717', int32), int(z'375A1A93', int32), int(z'377BA882', int32), int(z'378205FF', int32), &
       int(z'378637BD', int32), int(z'3796FEB5', int32), int(z'379B3073', int32), int(z'A1B877AA', int32) &
       ], [B,K])
  integer(int32), parameter :: QS_BITS(B,K) = reshape([ &
       int(z'3827C5AC', int32), int(z'38345AE6', int32), int(z'3840F020', int32), int(z'387BA882', int32), &
       int(z'38841EDE', int32), int(z'388A697B', int32), int(z'38A7C5AC', int32), int(z'38AE1049', int32), &
       int(z'38B45AE6', int32), int(z'38D1B717', int32), int(z'38D801B4', int32), int(z'38DE4C51', int32) &
       ], [B,K])
  integer(int32), parameter :: QG_BITS(B,K) = reshape([ &
       int(z'36EAE18B', int32), int(z'36FF0381', int32), int(z'370992BB', int32), int(z'37388CA4', int32), &
       int(z'37429D9F', int32), int(z'374CAE9A', int32), int(z'377BA882', int32), int(z'3782DCBF', int32), &
       int(z'3787E53C', int32), int(z'379F6230', int32), int(z'37A46AAE', int32), int(z'37A9732B', int32) &
       ], [B,K])
  integer(int32), parameter :: NCCN_BITS(B,K) = reshape([ &
       int(z'4E3EBC20', int32), int(z'4ECAA7E2', int32), int(z'4F38C63F', int32), int(z'4E3EBC20', int32), &
       int(z'4ECAA7E2', int32), int(z'4F38C63F', int32), int(z'4E3EBC20', int32), int(z'4ECAA7E2', int32), &
       int(z'4F38C63F', int32), int(z'4E3EBC20', int32), int(z'4ECAA7E2', int32), int(z'4F38C63F', int32) &
       ], [B,K])
  integer(int32), parameter :: NC_BITS(B,K) = reshape([ &
       int(z'4C189680', int32), int(z'4C1A9C14', int32), int(z'4C1CA1A8', int32), int(z'4C2469D8', int32), &
       int(z'4C266F6C', int32), int(z'4C287500', int32), int(z'4C303D30', int32), int(z'4C3242C4', int32), &
       int(z'4C344858', int32), int(z'4C3C1088', int32), int(z'4C3E161C', int32), int(z'4C401BB0', int32) &
       ], [B,K])
  integer(int32), parameter :: NI_BITS(B,K) = reshape([ &
       int(z'462BE000', int32), int(z'4A127C00', int32), int(z'4638B000', int32), int(z'46561000', int32), &
       int(z'465C7800', int32), int(z'4662E000', int32), int(z'46802000', int32), int(z'46835400', int32), &
       int(z'46868800', int32), int(z'46953800', int32), int(z'46986C00', int32), int(z'469BA000', int32) &
       ], [B,K])
  integer(int32), parameter :: NR_BITS(B,K) = reshape([ &
       int(z'44960000', int32), int(z'449BE000', int32), int(z'44A1C000', int32), int(z'44BCC000', int32), &
       int(z'44C2A000', int32), int(z'44C88000', int32), int(z'44E38000', int32), int(z'44E96000', int32), &
       int(z'44EF4000', int32), int(z'45052000', int32), int(z'45081000', int32), int(z'450B0000', int32) &
       ], [B,K])
  integer(int32), parameter :: BG_BITS(B,K) = reshape([ &
       int(z'322BCC77', int32), int(z'3237D319', int32), int(z'3243D9BB', int32), int(z'327084A7', int32), &
       int(z'327C8B49', int32), int(z'328448F5', int32), int(z'329A9E6B', int32), int(z'32A0A1BC', int32), &
       int(z'32A6A50D', int32), int(z'32BCFA83', int32), int(z'32C2FDD4', int32), int(z'32C90125', int32) &
       ], [B,K])
  integer(int32), parameter :: RHO_BITS(B,K) = reshape([ &
       int(z'3EE66666', int32), int(z'3EEF1AA0', int32), int(z'3EF7CED9', int32), int(z'3F2B851F', int32), &
       int(z'3F2FDF3B', int32), int(z'3F343958', int32), int(z'3F63D70A', int32), int(z'3F683127', int32), &
       int(z'3F6C8B44', int32), int(z'3F8E147B', int32), int(z'3F904189', int32), int(z'3F926E98', int32) &
       ], [B,K])
  integer(int32), parameter :: PII_BITS(B,K) = reshape([ &
       int(z'3F1EB852', int32), int(z'3F218937', int32), int(z'3F245A1D', int32), int(z'3F30A3D7', int32), &
       int(z'3F3374BC', int32), int(z'3F3645A2', int32), int(z'3F428F5C', int32), int(z'3F456042', int32), &
       int(z'3F483127', int32), int(z'3F547AE1', int32), int(z'3F574BC7', int32), int(z'3F5A1CAC', int32) &
       ], [B,K])
  integer(int32), parameter :: P_BITS(B,K) = reshape([ &
       int(z'46EA6000', int32), int(z'46EA6000', int32), int(z'46EA6000', int32), int(z'47435000', int32), &
       int(z'47435000', int32), int(z'47435000', int32), int(z'4788B800', int32), int(z'4788B800', int32), &
       int(z'4788B800', int32), int(z'47AFC800', int32), int(z'47AFC800', int32), int(z'47AFC800', int32) &
       ], [B,K])
  integer(int32), parameter :: DELZ_BITS(B,K) = reshape([ &
       int(z'43960000', int32), int(z'439C8000', int32), int(z'43A30000', int32), int(z'43C30000', int32), &
       int(z'43C98000', int32), int(z'43D00000', int32), int(z'43F00000', int32), int(z'43F68000', int32), &
       int(z'43FD0000', int32), int(z'440E8000', int32), int(z'4411C000', int32), int(z'44150000', int32) &
       ], [B,K])
  integer(int32), parameter :: XLAND_BITS(B) = [ &
       int(z'3F800000', int32), int(z'40000000', int32), int(z'3F800000', int32) &
       ]

  integer(int32), parameter :: DT_BITS = int(z'42700000', int32)
  integer(int32), parameter :: NCMIN_LAND_BITS = int(z'4CBEBC20', int32)
  integer(int32), parameter :: NCMIN_SEA_BITS = int(z'4CBEBC20', int32)
  integer(int32), parameter :: QMIN_BITS = int(z'26901D7D', int32)
  integer(int32), parameter :: CCN0_BITS = int(z'4C8583B0', int32)
  integer(int32), parameter :: SCALE_H_BITS = int(z'443B8000', int32)
end module g33_fixture_v1
