! GENERATED by harness/g33_fixture_v1.py from g33_fixture_v1.json.
! Do not edit: run the generator and commit both outputs.
module g33_fixture_v1
  use, intrinsic :: iso_fortran_env, only: int32
  implicit none
  integer, parameter :: B = 1, K = 39
  character(len=*), parameter :: FIXTURE_ID = 'lc05_column_v1'
  character(len=*), parameter :: MANIFEST_SHA256 = '5cd9a835c82b8a7536f11215f23e5d9d1c4348588785d2d80bc9116c63dd3cd6'
  character(len=*), parameter :: FIXTURE_SHA256 = 'bc5fd972f941f1790419de4a2c31b3d2aeb32267c7bad86b2b3f906457724788'
  character(len=*), parameter :: PARAMETER_SHA256 = 'fb1b87f217b3fdbd8c4decb1471d91883f50a03bd64ee8441a229a0e02b7a869'
  character(len=*), parameter :: FORTRAN_PARAMETER_SHA256 = 'f1008f2ec5629d7dcaa0e5305771163c7b7651cc112b3ceea6a4ad4b06caf39b'

  integer(int32), parameter :: TH_BITS(B,K) = reshape([ &
       int(z'43EED1E0', int32), int(z'43E73929', int32), int(z'43E02EE2', int32), int(z'43D9AC11', int32), &
       int(z'43D3A90A', int32), int(z'43CE1E67', int32), int(z'43C90414', int32), int(z'43C432AB', int32), &
       int(z'43BFDC49', int32), int(z'43BBF89B', int32), int(z'43B886DF', int32), int(z'43B5A3FF', int32), &
       int(z'43B33036', int32), int(z'43B125E7', int32), int(z'43AF794C', int32), int(z'43AE241D', int32), &
       int(z'43AD0411', int32), int(z'43ABEAFD', int32), int(z'43AA7975', int32), int(z'43A86D34', int32), &
       int(z'43A638C4', int32), int(z'43A40EC8', int32), int(z'43A1AEEF', int32), int(z'43A03F9C', int32), &
       int(z'439EC233', int32), int(z'439D8A82', int32), int(z'439C68B7', int32), int(z'439B2C33', int32), &
       int(z'4399EBBF', int32), int(z'4398E2F9', int32), int(z'4398094C', int32), int(z'439750F1', int32), &
       int(z'4396B097', int32), int(z'439620F2', int32), int(z'43958485', int32), int(z'43950ABD', int32), &
       int(z'4394B549', int32), int(z'43947561', int32), int(z'4394332F', int32) &
       ], [B,K])
  integer(int32), parameter :: QV_BITS(B,K) = reshape([ &
       int(z'365610FE', int32), int(z'362C74B3', int32), int(z'361C0C00', int32), int(z'361B7702', int32), &
       int(z'362DCF38', int32), int(z'365D97D0', int32), int(z'36984229', int32), int(z'36BE21AA', int32), &
       int(z'370CBAB0', int32), int(z'37638D48', int32), int(z'37C51BAD', int32), int(z'383AB001', int32), &
       int(z'38A93B57', int32), int(z'39199ED7', int32), int(z'3983305A', int32), int(z'39C3BE2D', int32), &
       int(z'39E5FD2E', int32), int(z'39A50517', int32), int(z'3A137AB1', int32), int(z'3B0E63B0', int32), &
       int(z'3A8662C7', int32), int(z'3A530DCE', int32), int(z'3BA013BA', int32), int(z'3BF5E935', int32), &
       int(z'3C1248C8', int32), int(z'3C2D670A', int32), int(z'3C490B11', int32), int(z'3C5F346B', int32), &
       int(z'3C6FCCB8', int32), int(z'3C804491', int32), int(z'3C8845A3', int32), int(z'3C8F2182', int32), &
       int(z'3C946709', int32), int(z'3C97D890', int32), int(z'3C97AF51', int32), int(z'3C97B1E0', int32), &
       int(z'3C972C2A', int32), int(z'3C96AA2D', int32), int(z'3C97B35F', int32) &
       ], [B,K])
  integer(int32), parameter :: QC_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'39CF0E6E', int32), &
       int(z'39E69332', int32), int(z'3A0BF19F', int32), int(z'3A15F3E1', int32), int(z'3A07E522', int32), &
       int(z'39E17D8C', int32), int(z'39B50A15', int32), int(z'3994CB19', int32), int(z'39796124', int32), &
       int(z'3953A8AD', int32), int(z'3933A00D', int32), int(z'3799AF70', int32), int(z'377701F0', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: QR_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'39A8D950', int32), &
       int(z'3A02163C', int32), int(z'3A1A0E71', int32), int(z'3A200E97', int32), int(z'3A1957FA', int32), &
       int(z'3A0A7ADE', int32), int(z'3A2229B5', int32), int(z'3A228F70', int32), int(z'3A1CFAEE', int32), &
       int(z'3A1A0F97', int32), int(z'3A180118', int32), int(z'3A15E538', int32), int(z'3A14D8B7', int32), &
       int(z'3A13C030', int32), int(z'3A12B215', int32), int(z'39A4886E', int32) &
       ], [B,K])
  integer(int32), parameter :: QI_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: QS_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'330A3823', int32), int(z'366F0561', int32), &
       int(z'36F699E9', int32), int(z'373E441A', int32), int(z'379A2AFD', int32), int(z'381C4206', int32), &
       int(z'38657EC6', int32), int(z'384F1905', int32), int(z'3799F9BE', int32), int(z'378AFCA0', int32), &
       int(z'38930A07', int32), int(z'39DEDE82', int32), int(z'3A3BCD5F', int32), int(z'38589EEE', int32), &
       int(z'37A59B48', int32), int(z'3AB8BB8E', int32), int(z'3A479EEB', int32), int(z'386EDC5A', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: QG_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'348FF25A', int32), int(z'342AF7DF', int32), &
       int(z'329D7F65', int32), int(z'363E3948', int32), int(z'39116D42', int32), int(z'3841809E', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: NCCN_BITS(B,K) = reshape([ &
       int(z'4B1A0CDB', int32), int(z'4B1A6AEB', int32), int(z'4B1AE069', int32), int(z'4B1B7358', int32), &
       int(z'4B1C2B52', int32), int(z'4B1D1214', int32), int(z'4B1E3419', int32), int(z'4B1FA17B', int32), &
       int(z'4B216ECA', int32), int(z'4B23B749', int32), int(z'4B269EDA', int32), int(z'4B2A551D', int32), &
       int(z'4B2F1AA0', int32), int(z'4B35460A', int32), int(z'4B3D4D63', int32), int(z'4B47D294', int32), &
       int(z'4B55B60F', int32), int(z'4B682D5F', int32), int(z'4B80708B', int32), int(z'4B910A6E', int32), &
       int(z'4BA7750C', int32), int(z'4BC5B479', int32), int(z'4BEAD768', int32), int(z'4C0BB3B4', int32), &
       int(z'4C25D9C1', int32), int(z'4C43E055', int32), int(z'4C65C7D0', int32), int(z'4C85B65D', int32), &
       int(z'4C99EA4E', int32), int(z'4CAEBE87', int32), int(z'4CC36726', int32), int(z'4CD72216', int32), &
       int(z'4CE9514C', int32), int(z'4CF98B8B', int32), int(z'4D03CF7E', int32), int(z'4D09C458', int32), &
       int(z'4D0EB504', int32), int(z'4D12BDB7', int32), int(z'4D15FE3E', int32) &
       ], [B,K])
  integer(int32), parameter :: NC_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'4C074A5B', int32), int(z'4C023C42', int32), int(z'4BD1BD25', int32), &
       int(z'4C53402C', int32), int(z'4C41DC25', int32), int(z'4C1E4A5F', int32), int(z'4C2CEF50', int32), &
       int(z'4C0BD867', int32), int(z'4B61E8DA', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: NI_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'3A919807', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: NR_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'44681C4F', int32), &
       int(z'4489EEE8', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'42B8A87A', int32), &
       int(z'43BCE9E3', int32), int(z'43F3B05D', int32), int(z'440050C1', int32), int(z'43FA101C', int32), &
       int(z'43F3A513', int32), int(z'43ED9DE7', int32), int(z'43EB02A4', int32) &
       ], [B,K])
  integer(int32), parameter :: BG_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32), &
       int(z'00000000', int32), int(z'00000000', int32), int(z'00000000', int32) &
       ], [B,K])
  integer(int32), parameter :: RHO_BITS(B,K) = reshape([ &
       int(z'3DB6BDC4', int32), int(z'3DCB85FD', int32), int(z'3DE25F41', int32), int(z'3DFB7A1C', int32), &
       int(z'3E0B80DF', int32), int(z'3E1A9059', int32), int(z'3E2B0102', int32), int(z'3E3D0854', int32), &
       int(z'3E508C07', int32), int(z'3E65A01B', int32), int(z'3E7C531C', int32), int(z'3E8A42E3', int32), &
       int(z'3E97341F', int32), int(z'3EA503AF', int32), int(z'3EB3BD46', int32), int(z'3EC36B52', int32), &
       int(z'3ED43D17', int32), int(z'3EE681FB', int32), int(z'3EFACC4C', int32), int(z'3F08CF00', int32), &
       int(z'3F15B398', int32), int(z'3F23247B', int32), int(z'3F300EDB', int32), int(z'3F3CC35F', int32), &
       int(z'3F495081', int32), int(z'3F552BE6', int32), int(z'3F60855E', int32), int(z'3F6BA7B9', int32), &
       int(z'3F764D6D', int32), int(z'3F7FD9CE', int32), int(z'3F841E54', int32), int(z'3F87C0D5', int32), &
       int(z'3F8ADDC1', int32), int(z'3F8D83FB', int32), int(z'3F8FC6EA', int32), int(z'3F91B6B3', int32), &
       int(z'3F9338A3', int32), int(z'3F946AB9', int32), int(z'3F9565AB', int32) &
       ], [B,K])
  integer(int32), parameter :: PII_BITS(B,K) = reshape([ &
       int(z'3EDCE96A', int32), int(z'3EE3AD03', int32), int(z'3EEAA7E7', int32), int(z'3EF1DF04', int32), &
       int(z'3EF95383', int32), int(z'3F0082E0', int32), int(z'3F047AB8', int32), int(z'3F089163', int32), &
       int(z'3F0CC72E', int32), int(z'3F111CF6', int32), int(z'3F15947C', int32), int(z'3F1A2FE7', int32), &
       int(z'3F1EF113', int32), int(z'3F23D929', int32), int(z'3F28E8DC', int32), int(z'3F2E2170', int32), &
       int(z'3F3383E8', int32), int(z'3F391131', int32), int(z'3F3EC97A', int32), int(z'3F44ACD8', int32), &
       int(z'3F4AC322', int32), int(z'3F50BFF8', int32), int(z'3F562BE1', int32), int(z'3F5B94CC', int32), &
       int(z'3F608C07', int32), int(z'3F6521F4', int32), int(z'3F695BCE', int32), int(z'3F6D3E9E', int32), &
       int(z'3F70C0FE', int32), int(z'3F73D8D0', int32), int(z'3F76856C', int32), int(z'3F78CA2B', int32), &
       int(z'3F7AADDF', int32), int(z'3F7C3B04', int32), int(z'3F7D6BA1', int32), int(z'3F7E74C2', int32), &
       int(z'3F7F45E9', int32), int(z'3F7FECB3', int32), int(z'3F8036D7', int32) &
       ], [B,K])
  integer(int32), parameter :: P_BITS(B,K) = reshape([ &
       int(z'45A4F2E7', int32), int(z'45B74F58', int32), int(z'45CBBDED', int32), int(z'45E2855A', int32), &
       int(z'45FBE8F4', int32), int(z'460C181A', int32), int(z'461BD354', int32), int(z'462D5063', int32), &
       int(z'4640BE44', int32), int(z'46565355', int32), int(z'466E50A9', int32), int(z'468480C8', int32), &
       int(z'46935C7F', int32), int(z'46A3E798', int32), int(z'46B65149', int32), int(z'46CACFFF', int32), &
       int(z'46E19F0F', int32), int(z'46FAFFB1', int32), int(z'470B9B11', int32), int(z'471B4633', int32), &
       int(z'472CC0A3', int32), int(z'473F460E', int32), int(z'47513AC7', int32), int(z'476450DA', int32), &
       int(z'4776E6B4', int32), int(z'4784802A', int32), int(z'478D4065', int32), int(z'4795A7E0', int32), &
       int(z'479D8BFE', int32), int(z'47A4BE97', int32), int(z'47AB2785', int32), int(z'47B0BAD3', int32), &
       int(z'47B578B9', int32), int(z'47B96EA2', int32), int(z'47BC82F4', int32), int(z'47BF38AA', int32), &
       int(z'47C160EA', int32), int(z'47C31C7C', int32), int(z'47C47572', int32) &
       ], [B,K])
  integer(int32), parameter :: DELZ_BITS(B,K) = reshape([ &
       int(z'44201BF9', int32), int(z'441FDD53', int32), int(z'441FD40E', int32), int(z'441FFCF8', int32), &
       int(z'44205ADF', int32), int(z'4420F10B', int32), int(z'4421C380', int32), int(z'4422BA4A', int32), &
       int(z'442405F4', int32), int(z'4425A75F', int32), int(z'4427A398', int32), int(z'442A1B8C', int32), &
       int(z'442CFA0E', int32), int(z'443043D9', int32), int(z'4433F88A', int32), int(z'44381E13', int32), &
       int(z'443C8FE8', int32), int(z'444113E5', int32), int(z'44456BA2', int32), int(z'4449964F', int32), &
       int(z'444CAA01', int32), int(z'443E9F8B', int32), int(z'4430EC8D', int32), int(z'4423A6B8', int32), &
       int(z'4416D59D', int32), int(z'440B1320', int32), int(z'44001B43', int32), int(z'43E7E0F2', int32), &
       int(z'43CD33AE', int32), int(z'43B203F2', int32), int(z'43978574', int32), int(z'437D6B6C', int32), &
       int(z'43509ADC', int32), int(z'432960B2', int32), int(z'4307E62C', int32), int(z'42D802CB', int32), &
       int(z'42AA86C1', int32), int(z'4285DC76', int32), int(z'425133C7', int32) &
       ], [B,K])
  integer(int32), parameter :: XLAND_BITS(B) = [ &
       int(z'40000000', int32) &
       ]

  integer(int32), parameter :: DT_BITS = int(z'42700000', int32)
  integer(int32), parameter :: NCMIN_LAND_BITS = int(z'4CBEBC20', int32)
  integer(int32), parameter :: NCMIN_SEA_BITS = int(z'4BBEBC20', int32)
  integer(int32), parameter :: QMIN_BITS = int(z'26901D7D', int32)
  integer(int32), parameter :: CCN0_BITS = int(z'4C8583B0', int32)
  integer(int32), parameter :: SCALE_H_BITS = int(z'443B8000', int32)
end module g33_fixture_v1
