! GENERATED by harness/g33_fixture_v1.py from g33_fixture_v1.json.
! Do not edit: run the generator and commit both outputs.
module g33_fixture_v1
  use, intrinsic :: iso_fortran_env, only: int32
  implicit none
  integer, parameter :: B = 3, K = 4
  character(len=*), parameter :: FIXTURE_ID = 'arithmetic_synthetic_v1'
  character(len=*), parameter :: MANIFEST_SHA256 = 'db44bc2defae793decddfc1a356eba977513afdac912e7c2b09cc82922247d2e'
  character(len=*), parameter :: FIXTURE_SHA256 = '18ea733b447986774a9effdf7562be21822d5226733307a5c7bfa0fca613f0f3'
  character(len=*), parameter :: PARAMETER_SHA256 = '4b1c84ef3186a843c7593b0b876c373e22af6ecac5a6ce1c198847b1204d32ef'
  character(len=*), parameter :: FORTRAN_PARAMETER_SHA256 = 'f1008f2ec5629d7dcaa0e5305771163c7b7651cc112b3ceea6a4ad4b06caf39b'

  integer(int32), parameter :: TH_BITS(B,K) = reshape([ &
       int(z'43910000', int32), int(z'43860000', int32), int(z'43720000', int32), int(z'4390C000', int32), &
       int(z'4385C000', int32), int(z'43718000', int32), int(z'43908000', int32), int(z'43858000', int32), &
       int(z'43710000', int32), int(z'43904000', int32), int(z'43854000', int32), int(z'43708000', int32) &
       ], [B,K])
  integer(int32), parameter :: QV_BITS(B,K) = reshape([ &
       int(z'3A83126F', int32), int(z'3A85B185', int32), int(z'3A88509C', int32), int(z'3A83126F', int32), &
       int(z'3A85B185', int32), int(z'3A88509C', int32), int(z'3A83126F', int32), int(z'3A85B185', int32), &
       int(z'3A88509C', int32), int(z'3A83126F', int32), int(z'3A85B185', int32), int(z'3A88509C', int32) &
       ], [B,K])
  integer(int32), parameter :: QC_BITS(B,K) = reshape([ &
       int(z'358637BD', int32), int(z'358637BD', int32), int(z'358637BD', int32), int(z'3593A3B6', int32), &
       int(z'3593A3B6', int32), int(z'3593A3B6', int32), int(z'35A10FB0', int32), int(z'35A10FB0', int32), &
       int(z'35A10FB0', int32), int(z'35AE7BA9', int32), int(z'35AE7BA9', int32), int(z'35AE7BA9', int32) &
       ], [B,K])
  integer(int32), parameter :: QR_BITS(B,K) = reshape([ &
       int(z'3827C5AC', int32), int(z'37A7C5AC', int32), int(z'36A7C5AC', int32), int(z'3813A3B6', int32), &
       int(z'3793A3B6', int32), int(z'3693A3B6', int32), int(z'37FF0381', int32), int(z'377F0381', int32), &
       int(z'367F0381', int32), int(z'37D6BF95', int32), int(z'3756BF95', int32), int(z'3656BF95', int32) &
       ], [B,K])
  integer(int32), parameter :: QI_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'37A7C5AC', int32), int(z'3851B717', int32), int(z'00000000', int32), &
       int(z'3793A3B6', int32), int(z'38388CA4', int32), int(z'00000000', int32), int(z'377F0381', int32), &
       int(z'381F6230', int32), int(z'00000000', int32), int(z'3756BF95', int32), int(z'380637BD', int32) &
       ], [B,K])
  integer(int32), parameter :: QS_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'3727C5AC', int32), int(z'37A7C5AC', int32), int(z'00000000', int32), &
       int(z'3713A3B6', int32), int(z'3793A3B6', int32), int(z'00000000', int32), int(z'36FF0381', int32), &
       int(z'377F0381', int32), int(z'00000000', int32), int(z'36D6BF95', int32), int(z'3756BF95', int32) &
       ], [B,K])
  integer(int32), parameter :: QG_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'36A7C5AC', int32), int(z'36A7C5AC', int32), int(z'00000000', int32), &
       int(z'3693A3B6', int32), int(z'3693A3B6', int32), int(z'00000000', int32), int(z'367F0381', int32), &
       int(z'367F0381', int32), int(z'00000000', int32), int(z'3656BF95', int32), int(z'3656BF95', int32) &
       ], [B,K])
  integer(int32), parameter :: NCCN_BITS(B,K) = reshape([ &
       int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), &
       int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), &
       int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), int(z'4E6E6B28', int32), int(z'4E6E6B28', int32) &
       ], [B,K])
  integer(int32), parameter :: NC_BITS(B,K) = reshape([ &
       int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), &
       int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), &
       int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), int(z'4CBEBC20', int32), int(z'4CBEBC20', int32) &
       ], [B,K])
  integer(int32), parameter :: NI_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'469C4000', int32), int(z'47435000', int32), int(z'00000000', int32), &
       int(z'46898000', int32), int(z'472BE000', int32), int(z'00000000', int32), int(z'466D8000', int32), &
       int(z'47147000', int32), int(z'00000000', int32), int(z'46480000', int32), int(z'46FA0000', int32) &
       ], [B,K])
  integer(int32), parameter :: NR_BITS(B,K) = reshape([ &
       int(z'47C35000', int32), int(z'47435000', int32), int(z'469C4000', int32), int(z'47ABE000', int32), &
       int(z'472BE000', int32), int(z'46898000', int32), int(z'47947000', int32), int(z'47147000', int32), &
       int(z'466D8000', int32), int(z'477A0000', int32), int(z'46FA0000', int32), int(z'46480000', int32) &
       ], [B,K])
  integer(int32), parameter :: BG_BITS(B,K) = reshape([ &
       int(z'00000000', int32), int(z'322BCC77', int32), int(z'322BCC77', int32), int(z'00000000', int32), &
       int(z'32172ECF', int32), int(z'32172ECF', int32), int(z'00000000', int32), int(z'32029127', int32), &
       int(z'32029127', int32), int(z'00000000', int32), int(z'31DBE6FF', int32), int(z'31DBE6FF', int32) &
       ], [B,K])
  integer(int32), parameter :: RHO_BITS(B,K) = reshape([ &
       int(z'3F400000', int32), int(z'3F547AE1', int32), int(z'3F68F5C3', int32), int(z'3F47AE14', int32), &
       int(z'3F5C28F6', int32), int(z'3F70A3D7', int32), int(z'3F4F5C29', int32), int(z'3F63D70A', int32), &
       int(z'3F7851EC', int32), int(z'3F570A3D', int32), int(z'3F6B851F', int32), int(z'3F800000', int32) &
       ], [B,K])
  integer(int32), parameter :: PII_BITS(B,K) = reshape([ &
       int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32), &
       int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32), &
       int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32) &
       ], [B,K])
  integer(int32), parameter :: P_BITS(B,K) = reshape([ &
       int(z'47985800', int32), int(z'47985800', int32), int(z'47985800', int32), int(z'47A02800', int32), &
       int(z'47A02800', int32), int(z'47A02800', int32), int(z'47A7F800', int32), int(z'47A7F800', int32), &
       int(z'47A7F800', int32), int(z'47AFC800', int32), int(z'47AFC800', int32), int(z'47AFC800', int32) &
       ], [B,K])
  integer(int32), parameter :: DELZ_BITS(B,K) = reshape([ &
       int(z'45FA0000', int32), int(z'45FD2000', int32), int(z'46002000', int32), int(z'4601B000', int32), &
       int(z'46034000', int32), int(z'4604D000', int32), int(z'46066000', int32), int(z'4607F000', int32), &
       int(z'46098000', int32), int(z'460B1000', int32), int(z'460CA000', int32), int(z'460E3000', int32) &
       ], [B,K])
  integer(int32), parameter :: XLAND_BITS(B) = [ &
       int(z'3F800000', int32), int(z'3F800000', int32), int(z'3F800000', int32) &
       ]

  integer(int32), parameter :: DT_BITS = int(z'41A00000', int32)
  integer(int32), parameter :: NCMIN_LAND_BITS = int(z'41200000', int32)
  integer(int32), parameter :: NCMIN_SEA_BITS = int(z'41200000', int32)
  integer(int32), parameter :: QMIN_BITS = int(z'26901D7D', int32)
  integer(int32), parameter :: CCN0_BITS = int(z'4C8583B0', int32)
  integer(int32), parameter :: SCALE_H_BITS = int(z'443B8000', int32)
end module g33_fixture_v1
