#pragma once
// GENERATED by harness/g33_fixture_v1.py from g33_fixture_v1.json.
// Do not edit: run the generator and commit both outputs.
#include <array>
#include <cstdint>

namespace g33_fixture_v1 {
inline constexpr std::int64_t B = 3;
inline constexpr std::int64_t K = 4;
inline constexpr char FIXTURE_ID[] = "boundary_mapping_v1";
inline constexpr char MANIFEST_SHA256[] = "3d07922b98a29ce5cdb4037a8fd77f0f779b8f1441515f45c7d7edd432ce4f05";
inline constexpr char FIXTURE_SHA256[] = "0b959687ea995b997baf685ab9e51e9ab03c9e1258ac190be8a60326eaddb047";
inline constexpr char PARAMETER_SHA256[] = "fb1b87f217b3fdbd8c4decb1471d91883f50a03bd64ee8441a229a0e02b7a869";
inline constexpr char FORTRAN_PARAMETER_SHA256[] = "f1008f2ec5629d7dcaa0e5305771163c7b7651cc112b3ceea6a4ad4b06caf39b";

inline constexpr std::array<std::uint32_t, B * K> th_bits = {{0x43960000u, 0x439b8000u, 0x43a10000u, 0x43a68000u, 0x43978000u, 0x439d0000u, 0x43a28000u, 0x43a80000u, 0x43990000u, 0x439e8000u, 0x43a40000u, 0x43a98000u}};
inline constexpr std::array<std::uint32_t, B * K> qv_bits = {{0x3a83126fu, 0x3a83126fu, 0x3a83126fu, 0x3a83126fu, 0x3aded289u, 0x3aded289u, 0x3aded289u, 0x3aded289u, 0x3b2a64c3u, 0x3b2a64c3u, 0x3b2a64c3u, 0x3b2a64c3u}};
inline constexpr std::array<std::uint32_t, B * K> qc_bits = {{0x3951b717u, 0xa0ce9a81u, 0x39a7c5acu, 0x39c73abdu, 0x395d3fe2u, 0x398e1501u, 0x39ad8a11u, 0x39ccff22u, 0x3968c8acu, 0x3993d966u, 0x39b34e77u, 0x39d2c387u}};
inline constexpr std::array<std::uint32_t, B * K> qr_bits = {{0x391d4952u, 0x3951b717u, 0x3983126fu, 0x399d4952u, 0x3926b93du, 0x395b2703u, 0x3987ca64u, 0x39a20147u, 0x39302928u, 0x396496eeu, 0x398c825au, 0x39a6b93du}};
inline constexpr std::array<std::uint32_t, B * K> qi_bits = {{0x3716feb5u, 0x3749539cu, 0x377ba882u, 0x3796feb5u, 0x371f6230u, 0x3751b717u, 0x378205ffu, 0x379b3073u, 0x3727c5acu, 0x375a1a93u, 0x378637bdu, 0xa1b877aau}};
inline constexpr std::array<std::uint32_t, B * K> qs_bits = {{0x3827c5acu, 0x387ba882u, 0x38a7c5acu, 0x38d1b717u, 0x38345ae6u, 0x38841edeu, 0x38ae1049u, 0x38d801b4u, 0x3840f020u, 0x388a697bu, 0x38b45ae6u, 0x38de4c51u}};
inline constexpr std::array<std::uint32_t, B * K> qg_bits = {{0x36eae18bu, 0x37388ca4u, 0x377ba882u, 0x379f6230u, 0x36ff0381u, 0x37429d9fu, 0x3782dcbfu, 0x37a46aaeu, 0x370992bbu, 0x374cae9au, 0x3787e53cu, 0x37a9732bu}};
inline constexpr std::array<std::uint32_t, B * K> nccn_bits = {{0x4e3ebc20u, 0x4e3ebc20u, 0x4e3ebc20u, 0x4e3ebc20u, 0x4ecaa7e2u, 0x4ecaa7e2u, 0x4ecaa7e2u, 0x4ecaa7e2u, 0x4f38c63fu, 0x4f38c63fu, 0x4f38c63fu, 0x4f38c63fu}};
inline constexpr std::array<std::uint32_t, B * K> nc_bits = {{0x4c189680u, 0x4c2469d8u, 0x4c303d30u, 0x4c3c1088u, 0x4c1a9c14u, 0x4c266f6cu, 0x4c3242c4u, 0x4c3e161cu, 0x4c1ca1a8u, 0x4c287500u, 0x4c344858u, 0x4c401bb0u}};
inline constexpr std::array<std::uint32_t, B * K> ni_bits = {{0x462be000u, 0x46561000u, 0x46802000u, 0x46953800u, 0x4a127c00u, 0x465c7800u, 0x46835400u, 0x46986c00u, 0x4638b000u, 0x4662e000u, 0x46868800u, 0x469ba000u}};
inline constexpr std::array<std::uint32_t, B * K> nr_bits = {{0x44960000u, 0x44bcc000u, 0x44e38000u, 0x45052000u, 0x449be000u, 0x44c2a000u, 0x44e96000u, 0x45081000u, 0x44a1c000u, 0x44c88000u, 0x44ef4000u, 0x450b0000u}};
inline constexpr std::array<std::uint32_t, B * K> bg_bits = {{0x322bcc77u, 0x327084a7u, 0x329a9e6bu, 0x32bcfa83u, 0x3237d319u, 0x327c8b49u, 0x32a0a1bcu, 0x32c2fdd4u, 0x3243d9bbu, 0x328448f5u, 0x32a6a50du, 0x32c90125u}};
inline constexpr std::array<std::uint32_t, B * K> rho_bits = {{0x3ee66666u, 0x3f2b851fu, 0x3f63d70au, 0x3f8e147bu, 0x3eef1aa0u, 0x3f2fdf3bu, 0x3f683127u, 0x3f904189u, 0x3ef7ced9u, 0x3f343958u, 0x3f6c8b44u, 0x3f926e98u}};
inline constexpr std::array<std::uint32_t, B * K> pii_bits = {{0x3f1eb852u, 0x3f30a3d7u, 0x3f428f5cu, 0x3f547ae1u, 0x3f218937u, 0x3f3374bcu, 0x3f456042u, 0x3f574bc7u, 0x3f245a1du, 0x3f3645a2u, 0x3f483127u, 0x3f5a1cacu}};
inline constexpr std::array<std::uint32_t, B * K> p_bits = {{0x46ea6000u, 0x47435000u, 0x4788b800u, 0x47afc800u, 0x46ea6000u, 0x47435000u, 0x4788b800u, 0x47afc800u, 0x46ea6000u, 0x47435000u, 0x4788b800u, 0x47afc800u}};
inline constexpr std::array<std::uint32_t, B * K> delz_bits = {{0x43960000u, 0x43c30000u, 0x43f00000u, 0x440e8000u, 0x439c8000u, 0x43c98000u, 0x43f68000u, 0x4411c000u, 0x43a30000u, 0x43d00000u, 0x43fd0000u, 0x44150000u}};
inline constexpr std::array<std::uint32_t, B> xland_bits = {{0x3f800000u, 0x40000000u, 0x3f800000u}};

inline constexpr std::uint32_t dt_bits = 0x42700000u;
inline constexpr std::uint32_t ncmin_land_bits = 0x4cbebc20u;
inline constexpr std::uint32_t ncmin_sea_bits = 0x4bbebc20u;
inline constexpr std::uint32_t qmin_bits = 0x26901d7du;
inline constexpr std::uint32_t fortran_ccn0_bits = 0x4c8583b0u;
inline constexpr std::uint32_t fortran_scale_h_bits = 0x443b8000u;

}  // namespace g33_fixture_v1
