#pragma once
// GENERATED by harness/g33_fixture_v1.py from g33_fixture_v1.json.
// Do not edit: run the generator and commit both outputs.
#include <array>
#include <cstdint>

namespace g33_fixture_v1 {
inline constexpr std::int64_t B = 3;
inline constexpr std::int64_t K = 4;
inline constexpr char FIXTURE_ID[] = "arithmetic_synthetic_v1";
inline constexpr char MANIFEST_SHA256[] = "db44bc2defae793decddfc1a356eba977513afdac912e7c2b09cc82922247d2e";
inline constexpr char FIXTURE_SHA256[] = "18ea733b447986774a9effdf7562be21822d5226733307a5c7bfa0fca613f0f3";
inline constexpr char PARAMETER_SHA256[] = "4b1c84ef3186a843c7593b0b876c373e22af6ecac5a6ce1c198847b1204d32ef";
inline constexpr char FORTRAN_PARAMETER_SHA256[] = "f1008f2ec5629d7dcaa0e5305771163c7b7651cc112b3ceea6a4ad4b06caf39b";

inline constexpr std::array<std::uint32_t, B * K> th_bits = {{0x43910000u, 0x4390c000u, 0x43908000u, 0x43904000u, 0x43860000u, 0x4385c000u, 0x43858000u, 0x43854000u, 0x43720000u, 0x43718000u, 0x43710000u, 0x43708000u}};
inline constexpr std::array<std::uint32_t, B * K> qv_bits = {{0x3a83126fu, 0x3a83126fu, 0x3a83126fu, 0x3a83126fu, 0x3a85b185u, 0x3a85b185u, 0x3a85b185u, 0x3a85b185u, 0x3a88509cu, 0x3a88509cu, 0x3a88509cu, 0x3a88509cu}};
inline constexpr std::array<std::uint32_t, B * K> qc_bits = {{0x358637bdu, 0x3593a3b6u, 0x35a10fb0u, 0x35ae7ba9u, 0x358637bdu, 0x3593a3b6u, 0x35a10fb0u, 0x35ae7ba9u, 0x358637bdu, 0x3593a3b6u, 0x35a10fb0u, 0x35ae7ba9u}};
inline constexpr std::array<std::uint32_t, B * K> qr_bits = {{0x3827c5acu, 0x3813a3b6u, 0x37ff0381u, 0x37d6bf95u, 0x37a7c5acu, 0x3793a3b6u, 0x377f0381u, 0x3756bf95u, 0x36a7c5acu, 0x3693a3b6u, 0x367f0381u, 0x3656bf95u}};
inline constexpr std::array<std::uint32_t, B * K> qi_bits = {{0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x37a7c5acu, 0x3793a3b6u, 0x377f0381u, 0x3756bf95u, 0x3851b717u, 0x38388ca4u, 0x381f6230u, 0x380637bdu}};
inline constexpr std::array<std::uint32_t, B * K> qs_bits = {{0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x3727c5acu, 0x3713a3b6u, 0x36ff0381u, 0x36d6bf95u, 0x37a7c5acu, 0x3793a3b6u, 0x377f0381u, 0x3756bf95u}};
inline constexpr std::array<std::uint32_t, B * K> qg_bits = {{0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x36a7c5acu, 0x3693a3b6u, 0x367f0381u, 0x3656bf95u, 0x36a7c5acu, 0x3693a3b6u, 0x367f0381u, 0x3656bf95u}};
inline constexpr std::array<std::uint32_t, B * K> nccn_bits = {{0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u, 0x4e6e6b28u}};
inline constexpr std::array<std::uint32_t, B * K> nc_bits = {{0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u, 0x4cbebc20u}};
inline constexpr std::array<std::uint32_t, B * K> ni_bits = {{0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x469c4000u, 0x46898000u, 0x466d8000u, 0x46480000u, 0x47435000u, 0x472be000u, 0x47147000u, 0x46fa0000u}};
inline constexpr std::array<std::uint32_t, B * K> nr_bits = {{0x47c35000u, 0x47abe000u, 0x47947000u, 0x477a0000u, 0x47435000u, 0x472be000u, 0x47147000u, 0x46fa0000u, 0x469c4000u, 0x46898000u, 0x466d8000u, 0x46480000u}};
inline constexpr std::array<std::uint32_t, B * K> bg_bits = {{0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x322bcc77u, 0x32172ecfu, 0x32029127u, 0x31dbe6ffu, 0x322bcc77u, 0x32172ecfu, 0x32029127u, 0x31dbe6ffu}};
inline constexpr std::array<std::uint32_t, B * K> rho_bits = {{0x3f400000u, 0x3f47ae14u, 0x3f4f5c29u, 0x3f570a3du, 0x3f547ae1u, 0x3f5c28f6u, 0x3f63d70au, 0x3f6b851fu, 0x3f68f5c3u, 0x3f70a3d7u, 0x3f7851ecu, 0x3f800000u}};
inline constexpr std::array<std::uint32_t, B * K> pii_bits = {{0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u, 0x3f800000u}};
inline constexpr std::array<std::uint32_t, B * K> p_bits = {{0x47985800u, 0x47a02800u, 0x47a7f800u, 0x47afc800u, 0x47985800u, 0x47a02800u, 0x47a7f800u, 0x47afc800u, 0x47985800u, 0x47a02800u, 0x47a7f800u, 0x47afc800u}};
inline constexpr std::array<std::uint32_t, B * K> delz_bits = {{0x45fa0000u, 0x4601b000u, 0x46066000u, 0x460b1000u, 0x45fd2000u, 0x46034000u, 0x4607f000u, 0x460ca000u, 0x46002000u, 0x4604d000u, 0x46098000u, 0x460e3000u}};
inline constexpr std::array<std::uint32_t, B> xland_bits = {{0x3f800000u, 0x3f800000u, 0x3f800000u}};

inline constexpr std::uint32_t dt_bits = 0x41a00000u;
inline constexpr std::uint32_t ncmin_land_bits = 0x41200000u;
inline constexpr std::uint32_t ncmin_sea_bits = 0x41200000u;
inline constexpr std::uint32_t qmin_bits = 0x26901d7du;
inline constexpr std::uint32_t fortran_ccn0_bits = 0x4c8583b0u;
inline constexpr std::uint32_t fortran_scale_h_bits = 0x443b8000u;

}  // namespace g33_fixture_v1
